import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const id='11111111-0000-4000-8000-000000000001',buyer='11111111-0000-4000-8000-000000000002',order='22222222-0000-4000-8000-000000000001';
test('receipt outbox protects keys, snapshots historical amounts, claims once and bounds uncertain retries',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema private;create schema auth;create schema vault;
 grant usage on schema private,auth,public to authenticated,service_role;
 create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function private.require_prospect_admin() returns void language plpgsql as $$begin if auth.uid() is distinct from '${id}'::uuid then raise exception 'admin_access_required';end if;end$$;
 create table vault.secrets(id uuid primary key default gen_random_uuid(),name text,decrypted_secret text);
 create view vault.decrypted_secrets as select * from vault.secrets;
 create function vault.create_secret(k text,n text,d text) returns uuid language sql as $$insert into vault.secrets(name,decrypted_secret) values(n,k) returning id$$;
 create function vault.update_secret(i uuid,k text) returns void language sql as $$update vault.secrets set decrypted_secret=k where id=i$$;
 create table public.package_checkout_orders(id uuid primary key,client_id uuid,status text,payment_id uuid,livemode boolean,paid_at timestamptz,price_hkd integer,credits integer,package_name text);
 insert into public.package_checkout_orders values('${order}','${buyer}','paid','${id}',true,now()+interval '1 second',900,1,'Trial session');`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260918141719_official_receipts.sql',import.meta.url),'utf8'));
 const role=async r=>db.exec(`reset role;set role ${r}`);
 const snapshot={terms_version:'2026-09-15',amount_hkd:900,credits:1,package_name:'Trial session',email:'buyer@example.test'};
 const ensure=async (s=snapshot)=>(await db.query('select ensure_official_receipt($1,$2) d',[order,s])).rows[0].d;
 await role('anon');await assert.rejects(ensure(),/permission denied/);await assert.rejects(db.query('select receipt_worker_jobs()'),/permission denied/);
 await role('authenticated');await assert.rejects(ensure(),/permission denied/);await assert.rejects(db.query('select * from private.official_receipts'),/permission denied/);await assert.rejects(db.query('select receipt_mail_settings()'),/admin_access_required/);
 await db.exec(`select set_config('request.jwt.claim.sub','${id}',false)`);
 const settings=(await db.query("select receipt_mail_settings('re_synthetic_test_key',true) d")).rows[0].d;assert.equal(settings.configured,true);assert.equal(JSON.stringify(settings).includes('re_synthetic'),false);
 await role('service_role');await assert.rejects(ensure({...snapshot,amount_hkd:1}),/receipt_mismatch/);
 const receipt=await ensure();assert.equal(receipt.email_status,'queued');assert.match(receipt.receipt_number,/^SS-\d{4}-00000001$/);
 const retry=await ensure({...snapshot,email:'changed@example.test'});assert.equal(retry.document.email,'buyer@example.test');assert.equal(retry.receipt_number,receipt.receipt_number);
 const payload={to:['buyer@example.test'],subject:'Official Receipt'};
 const claim=async()=>(await db.query('select claim_receipt_email($1,$2) d',[order,payload])).rows[0].d;
 const first=await claim();assert.equal(first.attempt,1);assert.equal(await claim(),null);
 await db.query("select finish_receipt_email($1,1,'provider-id')",[order]);assert.equal(await claim(),null);
 assert.equal((await db.query('select receipt_worker_jobs() d')).rows[0].d.jobs.length,0);
 await role('postgres');await db.exec(`update private.official_receipts set email_status='sending',first_attempt_at=now()-interval '24 hours',lease_until=now()-interval '5 minutes',next_attempt_at=now()`);
 await role('service_role');assert.equal((await db.query('select receipt_worker_jobs() d')).rows[0].d.jobs.length,0);
 await role('postgres');assert.equal((await db.query('select email_status from private.official_receipts')).rows[0].email_status,'needs_review');
 // Historical purchases get a receipt on demand but are not automatically emailed.
 await db.exec(`delete from private.official_receipts;update public.package_checkout_orders set paid_at=now()-interval '1 day'`);
 await role('service_role');assert.equal((await ensure()).email_status,'not_requested');
});
