import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
import {waiverEmailPayload,sendWaiverEmails} from '../supabase/functions/official-receipts/waiver.js';
const uid='11111111-0000-4000-8000-000000000001',sig='22222222-0000-4000-8000-000000000001';
test('waiver signatures queue an immutable own-client email; restricted settings and claims protect delivery',async t=>{
 const db=new PGlite();t.after(()=>db.close());
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema private;create schema auth;create schema vault;
 grant usage on schema private,auth,public to authenticated,service_role;
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;
 create function private.active_studio_client_id() returns text language plpgsql as $$begin if auth.uid() is null then raise exception 'auth';end if;return 'client';end$$;
 create function private.require_prospect_admin() returns void language plpgsql as $$begin if current_setting('test.admin',true) is distinct from 'yes' then raise exception 'admin_access_required';end if;end$$;
 create table vault.secrets(id uuid primary key default gen_random_uuid(),name text,decrypted_secret text);
 create view vault.decrypted_secrets as select * from vault.secrets;
 create function vault.create_secret(k text,n text,d text) returns uuid language sql as $$insert into vault.secrets(name,decrypted_secret) values(n,k) returning id$$;
 create function vault.update_secret(i uuid,k text) returns void language sql as $$update vault.secrets set decrypted_secret=k where id=i$$;
 create table auth.users(id uuid,email text,email_confirmed_at timestamptz);
 create table public.client_waiver_documents(version text,title text,body jsonb);
 create table public.client_waiver_signatures(id uuid primary key,user_id uuid,version text,document_sha256 text,signed_name text,participant_name text,signer_capacity text,signed_at timestamptz);
 insert into auth.users values('${uid}','client@example.test',now());
 insert into public.client_waiver_documents values('v1','Waiver','{"sections":[{"paras":["Agreed terms"]}]}');`);
 await db.exec(await readFile(new URL('../supabase/migrations/20260919030453_waiver_confirmation_email.sql',import.meta.url),'utf8'));
 await db.exec(`insert into public.client_waiver_signatures values('${sig}','${uid}','v1','hash','Signer','Participant','self',now());update public.client_waiver_documents set body='{}';`);
 let row=(await db.query('select * from private.waiver_emails')).rows[0];assert.equal(row.document.body.sections[0].paras[0],'Agreed terms');
 await db.exec(`set role authenticated;select set_config('request.jwt.claim.sub','${uid}',false);`);
 assert.equal((await db.query('select my_waiver_email_status($1) d',[sig])).rows[0].d.status,'not_connected');
 await assert.rejects(db.query('select waiver_worker_jobs()'),/permission denied/);
 await assert.rejects(db.query('select waiver_mail_settings()'),/admin_access_required/);
 await db.exec("select set_config('test.admin','yes',false)");const settings=(await db.query("select waiver_mail_settings('re_synthetic_test_key',true) d")).rows[0].d;assert.equal(settings.configured,true);assert.equal(JSON.stringify(settings).includes('re_synthetic'),false);
 await db.exec("select set_config('request.jwt.claim.sub','11111111-0000-4000-8000-000000000099',false)");assert.equal((await db.query('select my_waiver_email_status($1) d',[sig])).rows[0].d,null);
 await db.exec('reset role;set role service_role');
 const jobs=(await db.query('select waiver_worker_jobs() d')).rows[0].d;assert.equal(jobs.jobs.length,1);
 const payload=waiverEmailPayload(row.document,jobs.sender);assert.match(payload.text,/Agreed terms/);assert.match(payload.text,/Signer/);assert.match(payload.text,/Version: v1/);
 const claim=async()=>(await db.query('select claim_waiver_email($1,$2) d',[sig,payload])).rows[0].d;
 assert.equal((await claim()).attempt,1);assert.equal(await claim(),null);
 await db.query('select finish_waiver_email($1,1,$2)',[sig,'provider-id']);assert.equal(await claim(),null);
 assert.equal((await db.query('select waiver_worker_jobs() d')).rows[0].d.jobs.length,0);
});
test('waiver delivery reports failures and retries use a stable idempotency key',async()=>{
 const d={email:'client@example.test',signed_at:'2026-09-19T00:00:00Z',body:{sections:[{paras:['<private>']}]},version:'v1',signed_name:'S',participant_name:'P',capacity:'self'};
 const payload=waiverEmailPayload(d,'cs@senses-studio.co');assert.match(payload.html,/&lt;private&gt;/);
 const calls=[];const admin={rpc:async(name,args)=>{calls.push([name,args]);return{data:name==='waiver_worker_jobs'?{configured:true,key:'test',sender:'cs@senses-studio.co',jobs:[{signature_id:sig,document:d}]}:name==='claim_waiver_email'?{payload,attempt:1}:null};}};
 const result=await sendWaiverEmails(admin,async(_url,opts)=>{assert.equal(opts.headers['Idempotency-Key'],`senses-waiver/${sig}`);throw Error('offline');});
 assert.equal(result.failed,1);assert.equal(result.sent,0);assert.equal(calls.at(-1)[1].p_provider_id,null);
});
